package CheckoutPlace;
import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import java.util.*;

public class checkoutPlace extends ViewableDigraph {
	String IN = "IN", OUT = "OUT", outOne = "1OUT", outTwo = "2OUT", outThree = "3OUT";
	public checkoutPlace() {
		super("checkoutPlace");
		addInport(IN);
		addOutport(OUT);
		ViewableAtomic Customer = new Customer("Customer");
		add(Customer);
		ViewableAtomic VIPCustomer = new Customer("VIPCustomer");
		add(VIPCustomer);
		ViewableAtomic Receptionist = new Receptionist("Receptionist");
		add(Receptionist);
		ViewableAtomic CasherOne = new Casher("CasherOne");
		add(CasherOne);
		ViewableAtomic CasherTwo = new Casher("CasherTwo");
		add(CasherTwo);
		ViewableAtomic CasherThree = new Casher("CasherThree");
		add(CasherThree);
		ViewableAtomic transducer = new Transducer("transducer");
		add(transducer);
		
		addCoupling(Customer, OUT, Receptionist, IN);
		addCoupling(VIPCustomer, OUT, Receptionist, IN);
		addCoupling(Receptionist,outOne,CasherOne,IN);
		addCoupling(Receptionist,outTwo,CasherTwo,IN);
		addCoupling(Receptionist,outThree,CasherThree,IN);
		addCoupling(CasherOne,OUT,transducer,IN);
		addCoupling(CasherTwo,OUT,transducer,IN);
		addCoupling(CasherThree,OUT,transducer,IN);
		addCoupling(transducer, OUT, this, OUT);
		addCoupling(transducer, OUT, Receptionist, IN);
		
		
}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1031, 639);
        if((ViewableComponent)withName("CasherOne")!=null)
             ((ViewableComponent)withName("CasherOne")).setPreferredLocation(new Point(358, 49));
        if((ViewableComponent)withName("CasherThree")!=null)
             ((ViewableComponent)withName("CasherThree")).setPreferredLocation(new Point(395, 447));
        if((ViewableComponent)withName("VIPCustomer")!=null)
             ((ViewableComponent)withName("VIPCustomer")).setPreferredLocation(new Point(4, 400));
        if((ViewableComponent)withName("transducer")!=null)
             ((ViewableComponent)withName("transducer")).setPreferredLocation(new Point(623, 44));
        if((ViewableComponent)withName("CasherTwo")!=null)
             ((ViewableComponent)withName("CasherTwo")).setPreferredLocation(new Point(373, 230));
        if((ViewableComponent)withName("Customer")!=null)
             ((ViewableComponent)withName("Customer")).setPreferredLocation(new Point(-2, 64));
        if((ViewableComponent)withName("Receptionist")!=null)
             ((ViewableComponent)withName("Receptionist")).setPreferredLocation(new Point(152, 235));
    }
}
