package CheckoutPlace;
import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import java.util.*;

public class checkoutPlace5 extends ViewableDigraph {
	String IN = "IN", OUT = "OUT", outOne = "1OUT", outTwo = "2OUT", outThree = "3OUT", outFour = "4OUT" , outFive = "5OUT";
	public checkoutPlace5() {
		super("checkoutPlace");
		addInport(IN);
		addOutport(OUT);
		ViewableAtomic Customer = new Customer("Customer");
		add(Customer);
		ViewableAtomic VIPCustomer = new Customer("VIPCustomer");
		add(VIPCustomer);
		ViewableAtomic Receptionist = new Receptionist5("Receptionist");
		add(Receptionist);
		ViewableAtomic CasherOne = new Casher("CasherOne");
		add(CasherOne);
		ViewableAtomic CasherTwo = new Casher("CasherTwo");
		add(CasherTwo);
		ViewableAtomic CasherThree = new Casher("CasherThree");
		add(CasherThree);
		ViewableAtomic CasherFour = new Casher("CasherFour");
		add(CasherFour);
		ViewableAtomic CasherFive = new Casher("CasherFive");
		add(CasherFive);
		ViewableAtomic transducer = new Transducer("transducer");
		add(transducer);
		
		addCoupling(Customer, OUT, Receptionist, IN);
		addCoupling(VIPCustomer, OUT, Receptionist, IN);
		addCoupling(Receptionist,outOne,CasherOne,IN);
		addCoupling(Receptionist,outTwo,CasherTwo,IN);
		addCoupling(Receptionist,outThree,CasherThree,IN);
		addCoupling(Receptionist,outFour,CasherFour,IN);
		addCoupling(Receptionist,outFive,CasherFive,IN);
		addCoupling(CasherOne,OUT,transducer,IN);
		addCoupling(CasherTwo,OUT,transducer,IN);
		addCoupling(CasherThree,OUT,transducer,IN);
		addCoupling(CasherFour,OUT,transducer,IN);
		addCoupling(CasherFive,OUT,transducer,IN);
		addCoupling(transducer, OUT, this, OUT);
		addCoupling(transducer, OUT, Receptionist, IN);
		
		
}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1031, 639);
        if((ViewableComponent)withName("CasherThree")!=null)
             ((ViewableComponent)withName("CasherThree")).setPreferredLocation(new Point(368, 217));
        if((ViewableComponent)withName("Receptionist")!=null)
             ((ViewableComponent)withName("Receptionist")).setPreferredLocation(new Point(90, 215));
        if((ViewableComponent)withName("transducer")!=null)
             ((ViewableComponent)withName("transducer")).setPreferredLocation(new Point(540, 127));
        if((ViewableComponent)withName("CasherFive")!=null)
             ((ViewableComponent)withName("CasherFive")).setPreferredLocation(new Point(348, 405));
        if((ViewableComponent)withName("CasherTwo")!=null)
             ((ViewableComponent)withName("CasherTwo")).setPreferredLocation(new Point(363, 123));
        if((ViewableComponent)withName("CasherOne")!=null)
             ((ViewableComponent)withName("CasherOne")).setPreferredLocation(new Point(347, 49));
        if((ViewableComponent)withName("Customer")!=null)
             ((ViewableComponent)withName("Customer")).setPreferredLocation(new Point(-26, 199));
        if((ViewableComponent)withName("VIPCustomer")!=null)
             ((ViewableComponent)withName("VIPCustomer")).setPreferredLocation(new Point(-9, 340));
        if((ViewableComponent)withName("CasherFour")!=null)
             ((ViewableComponent)withName("CasherFour")).setPreferredLocation(new Point(349, 319));
    }
}
